// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	src/proto/api.proto

It has these top-level messages:
	Event
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Example message
type Event struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// unix timestamp
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// magic number
	Magic int64 `protobuf:"varint,3,opt,name=magic" json:"magic,omitempty"`
	// message
	Message string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMagic() int64 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("src/proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x94, 0x52, 0xb9, 0x58,
	0x5d, 0xcb, 0x52, 0xf3, 0x4a, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12,
	0x73, 0x0b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x10, 0x02, 0x42, 0x22, 0x5c, 0xac, 0xb9,
	0x89, 0xe9, 0x99, 0xc9, 0x12, 0xcc, 0x60, 0x19, 0x08, 0x47, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5,
	0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x05, 0x6c, 0x10, 0x8c, 0x9b, 0xc4, 0x06, 0xb6, 0xcd, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xdf, 0xa2, 0x6b, 0x84, 0x00, 0x00, 0x00,
}
